#!/bin/bash

docker build \
  --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
  --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
  --build-arg COMMIT_MSG=$COMMIT_MSG \
  --build-arg DOCKER_REPO=$DOCKER_REPO \
  --build-arg DOCKERFILE_PATH=$DOCKERFILE_PATH \
  --build-arg CACHE_TAG=$CACHE_TAG \
  --build-arg IMAGE_NAME=$IMAGE_NAME \
  -f $DOCKERFILE_PATH \
  -t $IMAGE_NAME \
  .
